import React, { Component } from 'react';
import axios from 'axios';
import Sidebar from '../Sidebar/Sidebar';

// const BASE_URL = "https://my-json-server.typicode.com/themeland/netstorm-json-2/blogSingle";
export const initData = {
    "blogData": [
        {
            "image": "/img/blog/1.png",
            "title": "NFT sales and blockchain games continue to grow despite the recent market slump",
            "content_1": "Gen Z and growing interest throughout Asia have helped NFTs to shine brightly amidst volatility, according to a report from DappRadar.",
            "content_2": "January 2022 continues to be rough for crypto investors as current markets see turbulent fluctuations in the price of Bitcoin (BTC) and other cryptocurrencies. Some have attributed the slump to recent federal intentions to introduce new rate hikes, and the political turmoil in Kazakhstan, which significantly lowered the hash rate of Bitcoin. On Jan. 14, the price of Bitcoin dipped below $42,000 as traders continued to hold out hope for bullish signals.",
            "content_3": "Nonfungible token (NFT) trading and blockchain games, on the other hand, seem to have resisted the dip. According to reports from DappRadar, NFT transactions continued to increase amid declining crypto prices. The report stated that “the number of UAW connected to Ethereum NFT DApps grew by 43% since Q3 2021.” Numbers from the report also show that the money",
            "content_4": "generated by NFT trading went from $10.7 billion in Q3 2021 to $11.9 billion in the first ten days of 2022. Recent developments in the NFT space, such as the launch of the LooksRare marketplace, may have also contributed to this growth.",
            "content_5": "The report also stated that “blockchain games continue to be widely used,” and noted that they “represent 52% of the industry’s usage.” Expanding metaverse developments alongside the growing success of the play-to-earn model have also strengthened the case for blockchain games to continue growing throughout 2022.",
            "content_6": "The growing interest in NFTs and blockchain gaming during this market slump can partially be attributed to Chinese audiences, which coincides with the recent announcements from China that say that the country will begin developing its own non-crypto NFT industry. According to DappRadar’s report, “China is now the country with the most extensive user base…increasing 166% from the numbers registered in November.",
            "content_7": "Even though the United States is now second in terms of overall traffic, the country still saw 175,000 new users in the NFT ecosystem, a growth of around 38%. This comes in part from the growing interests among younger audiences as Millennials and Generation Z start to account for a higher percentage of traffic.",
            "content_8": "DappRadar reported that “30% of its traffic came from users from this age group… [with millennials] growing from the 36% observed from last year.",
            "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quam tortor, ultrices accumsan mauris eget, pulvinar tincidunt erat. Sed nisi nisi, rutrum sit amet elit.",
            "date": "Jul 12, 2021",
            "commentTitle": "Leave a Reply",
            "commentContent": "Sed mauris nulla, tempor eu est vel, dapibus hendrerit mauris.",
            "commentBtn": "POST COMMENT"
          },
          {
            "image": "/img/blog/2.png",
            "title": "7 NFT Games to Play-to-Earn in 2022",
            "content_1": "Earning an income from playing video games has traditionally been limited to e-sport athletes or content creators. With play-to-earn, the average gamer can now monetize their playing time via buying and selling in-game NFTs or completing objectives in exchange for cryptocurrency rewards. If you’re interested in learning more, you can read our helpful guide to getting crypto and NFTs via play-to-earn.",
            "content_2": "Binance NFT is at the forefront of Play-to-Earn gaming, with a vast collection of high-quality gaming drops and the first-ever Initial Game Offering (IGO) platform for emerging NFT gaming projects. If you’re looking for a quick way to start your NFT gaming adventures, you can begin by browsing our available collections. Keep reading to find out the seven play-to-earn NFT games you should look out for in 2022.",
            "content_3": "1. Mine of Dalarnia",
            "content_4": "Launched on the Binance Launchpool, Mines of Dalarnia is an action-adventure gaming project that features a unique blockchain-powered real-estate market. The player base is split into two cooperating factions, miners and landowners. Miners battle monsters and destroy blocks to find precious resources, while landowners provide the land and resources. Players can also team up with friends to defeat monsters, complete quests and unlock in-game rewards.",
            "image_1": "/img/blog/2.1.png",
            "content_5": "Mines of Dalarnia's in-game assets are available for purchase on the Binance NFT Marketplace via their upcoming IGO collection in Q1 of 2022. The in-game currency, DAR, is used for all in-game transactions, including upgrades, skill progression, governance, transaction fees and more.",
            "content_6": "2. My Neighbor Alice",
            "content_7": "My Neighbor Alice is a multiplayer world-building game that combines the best of both worlds, an engaging experience for regular gamers, and an ecosystem for NFT traders and collectors.",
            "image_2": "/img/blog/2.2.png",
            "content_8": "Players purchase and own virtual plots of land in the form of an NFT token from Alice or the marketplace. There is a scarce supply of available land, so prices fluctuate in the marketplace. If you’re an excellent landowner, you’ll unlock additional benefits through the in-game reputation system. In addition to land, players can buy and use in-game assets like houses, animals, veggies, decorations or cosmetic items for their avatar.",
            "content_9": "The primary in-game currency is the Alice token, which is also available for purchase on Binance. Alice tokens are used for in-game transactions, like buying land, and specific DeFi services like staking, collateralization and buyback.",
            "content_10": "To get started, you can check out Binance NFT's secondary marketplace for a wide array of My Neighbor Alice in-game assets, including previously sold-out mystery box items.",
            "content_11": "3. Mobox",
            "content_12": "Mobox is a cross-platform GameFi metaverse that combines gaming NFTs with DeFi yield farming. Players can acquire Mobox NFTs, also known as MOMOs, through Binance NFT Mystery Box launches or the Binance NFT secondary marketplace.",
            "content_13": "Players can farm, battle and generate crypto rewards with their MOMO NFTs. The platform also allows players to trade their MOMOs, stake them to farm MBOX tokens or use them as collateral within the MOBOX metaverse.",
            "image_3": "/img/blog/2.3.png",
            "content_14": "Mobox provides straightforward gameplay that combines free-to-play and play-to-earn mechanics. The game prioritizes NFT interoperability, enabling players to simultaneously use their MOBOX assets across multiple games.",
            "content_15": "4. Axie Infinity",
            "image_4": "/img/blog/2.4.png",
            "content_16": "Well-known amongst the crypto community, Axie Infinity is a Pokemon-inspired Play-to-earn game where players battle, raise and trade fantasy creatures called Axies. The game incentivizes players to pit their Axies against each other in exchange for an in-game currency called small love potions (SLP). Each Axie is also an NFT that can be bought or sold on NFT marketplaces.",
            "content_17": "5. Illuvium",
            "content_18": "Illuvium is an upcoming blockchain game in an open-world, RPG setting. Players travel across a fantasy world, defeating and catching creatures known as Illuvials. Once they’re in your collection, Illivuals can be used in battle against other players while you're questing, completing challenges or playing through Illuvium's story.",
            "image_5": "/img/blog/2.5.png",
            "content_19": "The core mechanic of the Illuvium project is collecting and customizing your NFT Illuvials. Each Illuvial has a corresponding affinity and class. There are five classes and five affinities, all with unique strengths and weaknesses. Your Illuvial becomes more powerful as you win battles and complete quests.",
            "content_20": "All of Illivium's in-game assets, including Illuvials and items, can be traded on an NFT marketplace. If you’re interested in earning Illuvium’s in-game currencies, ILV and sILV, you can purchase the token on Binance and start staking on Ilivium's platform, or you can stake partner tokens in their Flash Pools.",
            "content_21": "6. Sandbox",
            "content_22": "The Sandbox is a Play-to-Earn virtual metaverse, where users can own land, play games or even build their own game. Contribute to the virtual world as a collector, artist or game decider, or experience the different games as a regular player. If you’re looking to buy digital land or real estate, The Sandbox is one of the biggest names in the metaverse.",
            "image_6": "/img/blog/2.6.png",
            "content_23": "7. Aliens World",
            "content_24": "Alien Worlds is an NFT Metaverse spread over seven planets. The game’s goal is to earn in-game cryptocurrency, called Trilium (TLM), that can be traded for real money.",
            "image_7": "/img/blog/2.7.png",
            "content_25": "Players can mine TLM or send virtual spaceships on missions throughout the Metaverse to compete for a share of the TLM prize pool. Each traveler can receive up to five NFTs after completing a mission. The game also allows players to compete against each other on the BSC blockchain as they explore the different planets.",
            "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quam tortor, ultrices accumsan mauris eget, pulvinar tincidunt erat. Sed nisi nisi, rutrum sit amet elit.",
            "date": "Jul 12, 2021",
            "commentTitle": "Leave a Reply",
            "commentContent": "Sed mauris nulla, tempor eu est vel, dapibus hendrerit mauris.",
            "commentBtn": "POST COMMENT"
          },

    ]
    
}
class BlogSingle extends Component {
   constructor(props){
       super(props);
       this.state = {
           id: 0,
           data: [],
       };
   }
    async componentDidMount(){
        const id = this.props.id-1;
       await this.setState({
           id: id,
           data: initData.blogData[id]
        })
       console.log(id);
        
    }
    render() {
        return (
            <section className="single featured post-details">
                <div className="container">
                    <div className="row">
                        {/* Main */}
                        <div className="col-12 col-lg-8 p-0">
                            <div className="row">
                            {(this.props.id && this.state.data )
                                    ? (         
        
                                <div className="col-12 align-self-center">
                                    
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image} alt="" />
                                    </div>
                                    <h2 className="featured ml-0">{this.state.data.title}</h2>
                                    <p>{this.state.data.content_1}</p>
                                    {/* <blockquote>{this.state.data.quote}</blockquote> */}
                                    <p>{this.state.data.content_2}</p>
                                    <p>{this.state.data.content_3}</p>
                                    <p>{this.state.data.content_4}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_1} alt="" />
                                    </div>
                                    <p>{this.state.data.content_5}</p>
                                    <p>{this.state.data.content_6}</p>
                                    <p>{this.state.data.content_7}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_2} alt="" />
                                    </div>
                                    <p>{this.state.data.content_8}</p>
                                    <p>{this.state.data.content_9}</p>
                                    <p>{this.state.data.content_10}</p>
                                    <p>{this.state.data.content_11}</p>
                                    <p>{this.state.data.content_12}</p>
                                    <p>{this.state.data.content_13}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_3} alt="" />
                                    </div>
                                    <p>{this.state.data.content_14}</p>
                                    <p>{this.state.data.content_15}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_4} alt="" />
                                    </div>
                                    <p>{this.state.data.content_16}</p>
                                    <p>{this.state.data.content_17}</p>
                                    <p>{this.state.data.content_18}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_5} alt="" />
                                    </div>
                                    <p>{this.state.data.content_19}</p>
                                    <p>{this.state.data.content_20}</p>
                                    <p>{this.state.data.content_21}</p>
                                    <p>{this.state.data.content_22}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_6} alt="" />
                                    </div>
                                    <p>{this.state.data.content_23}</p>
                                    <p>{this.state.data.content_24}</p>
                                    <div className="blog-thumb">
                                        <img className="w-100" src={this.state.data.image_7} alt="" />
                                    </div>
                                    <p>{this.state.data.content_25}</p>
                                    <ul className="mb-5 post-holder">
                                        <li className="post-meta-item">
                                            <div className="date">
                                                <span className="posted-on">Posted On <a href="#" rel="bookmark"><time className="entry-date published updated" dateTime="2018-11-01T06:18:46+00:00">{this.state.data.date}</time></a></span>
                                            </div>
                                        </li>
                                    </ul>
                                    {/* <h3 className="comments-reply-text mb-3">{this.state.data.commentTitle}</h3>
                                    <p className="mt-3">{this.state.data.commentContent}</p>
                                    <form>
                                        <fieldset>
                                            <div className="row">
                                                <div className="col-12 col-lg-6 input-group p-0 pr-lg-3 mb-3">
                                                    <input type="text" name="name" data-minlength={3} placeholder="Name" required />
                                                </div>
                                                <div className="col-12 col-lg-6 input-group p-0 mb-3">
                                                    <input type="email" name="email" data-minlength={3} placeholder="Email" required />
                                                </div>
                                            </div>
                                            <div className="row">
                                                <div className="col-12 input-group p-0 mb-3">
                                                    <textarea name="message" data-minlength={3} rows={4} placeholder="Message" required defaultValue={""} />
                                                </div>
                                            </div>
                                            <div className="col-12 input-group p-0">
                                                <a className="btn btn-bordered-white text-white">{this.state.data.commentBtn}<i className="icon-login ml-2" /></a>
                                            </div>
                                        </fieldset>
                                    </form> */}
                                </div>
                                 ) : null }
                            </div>
                        </div>
                        {/* Sidebar */}
                        <Sidebar />
                    </div>
                </div>
            </section>
        );
    }
}

export default BlogSingle;